kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-docker-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-docker-k8s-app
  template:
    metadata:
      labels:
        app: react-docker-k8s-app
    spec:
      containers:
        - name: react-docker-k8s-app
          image: localhost:5000/react-docker-k8s-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always