kind: Service
apiVersion: v1
metadata:
  name: react-docker-k8s-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: react-docker-k8s-app